In [1]:
#9.จงสร้าง identity matrix แบบ 4x4
import numpy as np

In [2]:
x = np.eye(4, 4)
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
#10.จงหาว่า array ที่มีสมาชิก 100 ตัว เริ่มจาก 5 ถึง 25 มีผลต่างแต่ละตัวเท่ากับเท่าใด
x1 = np.linspace(5,25,100)
x1[1]-x1[0]

0.20202020202020243

In [10]:
#11.จงเขียนฟังก์ชั่น random ตัวเลขแบบ float ในช่วง 0-1 ขึ้นมา 1 ตัว
np.random.rand(1)

array([0.59320472])

In [17]:
#12.จงเขียนฟังก์ชั่นที่ random ตัวเลขแบบ int ในช่วง 50-100 โดยให้อยู่ในรูป Matrix 4x4 และ Transpose
x2=np.random.randint(50,100,(4,4))
x2

array([[67, 79, 73, 69],
       [62, 57, 80, 67],
       [57, 96, 83, 97],
       [51, 56, 59, 74]])

In [18]:
x2.T

array([[67, 62, 57, 51],
       [79, 57, 96, 56],
       [73, 80, 83, 59],
       [69, 67, 97, 74]])